CREATE TABLE "accommodations" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name_ar" text NOT NULL,
	"city" text NOT NULL,
	"province" text NOT NULL,
	"description_ar" text NOT NULL,
	"monthly_price_zar" integer NOT NULL,
	"room_type" text NOT NULL,
	"furnished" boolean DEFAULT true NOT NULL,
	"distance_to_airport" text,
	"wifi" boolean DEFAULT true NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "accommodations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "applications" (
	"id" text PRIMARY KEY NOT NULL,
	"full_name" text NOT NULL,
	"nationality" text NOT NULL,
	"phone" text NOT NULL,
	"whatsapp" text,
	"email" text NOT NULL,
	"current_license" text,
	"desired_license" text NOT NULL,
	"estimated_budget" text,
	"preferred_start" text,
	"notes" text,
	"status" text DEFAULT 'new' NOT NULL,
	"flight_school_id" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flight_schools" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name_ar" text NOT NULL,
	"name_en" text NOT NULL,
	"province" text NOT NULL,
	"city" text NOT NULL,
	"airport_name" text NOT NULL,
	"airport_code" text NOT NULL,
	"description_ar" text NOT NULL,
	"short_description_ar" text NOT NULL,
	"licenses" text NOT NULL,
	"training_type" text NOT NULL,
	"price_min_zar" integer NOT NULL,
	"price_max_zar" integer NOT NULL,
	"duration_months_min" integer NOT NULL,
	"duration_months_max" integer NOT NULL,
	"accepts_international" boolean DEFAULT true NOT NULL,
	"has_accommodation" boolean DEFAULT false NOT NULL,
	"aircraft_fleet" text NOT NULL,
	"rating" real DEFAULT 4.5 NOT NULL,
	"nino_ranking" integer DEFAULT 0 NOT NULL,
	"website_url" text,
	"hero_image_url" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"last_pricing_update" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "flight_schools_slug_unique" UNIQUE("slug")
);
