// Generated once from i18n-iso-countries (Arabic names) + libphonenumber-js
// (valid calling codes). Static so the browser only ships the phone
// validation library, not the full locale dataset.
export type Country = { code: string; name: string; dialCode: string };

export const COUNTRIES: Country[] = [
  { code: "SA", name: "السعودية", dialCode: "966" },
  { code: "AE", name: "الإمارات العربية المتحدة", dialCode: "971" },
  { code: "EG", name: "مصر", dialCode: "20" },
  { code: "KW", name: "الكويت", dialCode: "965" },
  { code: "QA", name: "قطر", dialCode: "974" },
  { code: "BH", name: "البحرين", dialCode: "973" },
  { code: "OM", name: "عمان", dialCode: "968" },
  { code: "JO", name: "الأردن", dialCode: "962" },
  { code: "IQ", name: "العراق", dialCode: "964" },
  { code: "SY", name: "سوريا", dialCode: "963" },
  { code: "LB", name: "لبنان", dialCode: "961" },
  { code: "PS", name: "فلسطين", dialCode: "970" },
  { code: "YE", name: "اليمن", dialCode: "967" },
  { code: "MA", name: "المغرب", dialCode: "212" },
  { code: "DZ", name: "الجزائر", dialCode: "213" },
  { code: "TN", name: "تونس", dialCode: "216" },
  { code: "LY", name: "ليبيا", dialCode: "218" },
  { code: "SD", name: "السودان", dialCode: "249" },
  { code: "IN", name: "الهند", dialCode: "91" },
  { code: "IS", name: "آيسلندا", dialCode: "354" },
  { code: "ET", name: "إثيوبيا", dialCode: "251" },
  { code: "AZ", name: "أذربيجان", dialCode: "994" },
  { code: "AM", name: "أرمينيا", dialCode: "374" },
  { code: "AW", name: "أروبا", dialCode: "297" },
  { code: "ER", name: "إريتريا", dialCode: "291" },
  { code: "ES", name: "إسبانيا", dialCode: "34" },
  { code: "AU", name: "أستراليا", dialCode: "61" },
  { code: "EE", name: "إستونيا", dialCode: "372" },
  { code: "IL", name: "إسرائيل", dialCode: "972" },
  { code: "AF", name: "أفغانستان", dialCode: "93" },
  { code: "IO", name: "إقليم المحيط الهندي البريطاني", dialCode: "246" },
  { code: "AR", name: "الأرجنتين", dialCode: "54" },
  { code: "EC", name: "الإكوادور", dialCode: "593" },
  { code: "UY", name: "الأوروغواي", dialCode: "598" },
  { code: "AL", name: "ألبانيا", dialCode: "355" },
  { code: "BR", name: "البرازيل", dialCode: "55" },
  { code: "PT", name: "البرتغال", dialCode: "351" },
  { code: "BA", name: "البوسنة والهرسك", dialCode: "387" },
  { code: "ME", name: "الجبل الأسود", dialCode: "382" },
  { code: "BQ", name: "الجزر الكاريبية الهولندية", dialCode: "599" },
  { code: "DK", name: "الدنمارك", dialCode: "45" },
  { code: "CV", name: "الرأس الأخضر", dialCode: "238" },
  { code: "SV", name: "السلفادور", dialCode: "503" },
  { code: "SN", name: "السنغال", dialCode: "221" },
  { code: "SE", name: "السويد", dialCode: "46" },
  { code: "EH", name: "الصحراء الغربية", dialCode: "212" },
  { code: "SO", name: "الصومال", dialCode: "252" },
  { code: "CN", name: "الصين", dialCode: "86" },
  { code: "GA", name: "الغابون", dialCode: "241" },
  { code: "VA", name: "الفاتيكان", dialCode: "39" },
  { code: "PH", name: "الفلبين", dialCode: "63" },
  { code: "CM", name: "الكاميرون", dialCode: "237" },
  { code: "DE", name: "ألمانيا", dialCode: "49" },
  { code: "HU", name: "المجر", dialCode: "36" },
  { code: "MX", name: "المكسيك", dialCode: "52" },
  { code: "GB", name: "المملكة المتحدة", dialCode: "44" },
  { code: "NO", name: "النرويج", dialCode: "47" },
  { code: "AT", name: "النمسا", dialCode: "43" },
  { code: "NE", name: "النيجر", dialCode: "227" },
  { code: "US", name: "الولايات المتحدة", dialCode: "1" },
  { code: "JP", name: "اليابان", dialCode: "81" },
  { code: "GR", name: "اليونان", dialCode: "30" },
  { code: "AG", name: "أنتيغوا وباربودا", dialCode: "1" },
  { code: "AD", name: "أندورا", dialCode: "376" },
  { code: "ID", name: "إندونيسيا", dialCode: "62" },
  { code: "AO", name: "أنغولا", dialCode: "244" },
  { code: "AI", name: "أنغويلا", dialCode: "1" },
  { code: "UZ", name: "أوزبكستان", dialCode: "998" },
  { code: "UG", name: "أوغندا", dialCode: "256" },
  { code: "UA", name: "أوكرانيا", dialCode: "380" },
  { code: "IR", name: "إيران", dialCode: "98" },
  { code: "IE", name: "أيرلندا", dialCode: "353" },
  { code: "IT", name: "إيطاليا", dialCode: "39" },
  { code: "PG", name: "بابوا غينيا الجديدة", dialCode: "675" },
  { code: "PY", name: "باراغواي", dialCode: "595" },
  { code: "BB", name: "باربادوس", dialCode: "1" },
  { code: "PK", name: "باكستان", dialCode: "92" },
  { code: "PW", name: "بالاو", dialCode: "680" },
  { code: "BS", name: "باهاماس", dialCode: "1" },
  { code: "BM", name: "برمودا", dialCode: "1" },
  { code: "BN", name: "بروناي", dialCode: "673" },
  { code: "BE", name: "بلجيكا", dialCode: "32" },
  { code: "BG", name: "بلغاريا", dialCode: "359" },
  { code: "BZ", name: "بليز", dialCode: "501" },
  { code: "BD", name: "بنغلاديش", dialCode: "880" },
  { code: "PA", name: "بنما", dialCode: "507" },
  { code: "BJ", name: "بنين", dialCode: "229" },
  { code: "BT", name: "بوتان", dialCode: "975" },
  { code: "BW", name: "بوتسوانا", dialCode: "267" },
  { code: "PR", name: "بورتوريكو", dialCode: "1" },
  { code: "BF", name: "بوركينا فاسو", dialCode: "226" },
  { code: "MM", name: "بورما", dialCode: "95" },
  { code: "BI", name: "بوروندي", dialCode: "257" },
  { code: "PL", name: "بولندا", dialCode: "48" },
  { code: "BO", name: "بوليفيا", dialCode: "591" },
  { code: "PF", name: "بولينزيا الفرنسية", dialCode: "689" },
  { code: "PE", name: "بيرو", dialCode: "51" },
  { code: "TZ", name: "تانزانيا", dialCode: "255" },
  { code: "TH", name: "تايلاند", dialCode: "66" },
  { code: "TW", name: "تايوان", dialCode: "886" },
  { code: "TM", name: "تركمانستان", dialCode: "993" },
  { code: "TR", name: "تركيا", dialCode: "90" },
  { code: "TT", name: "ترينيداد وتوباغو", dialCode: "1" },
  { code: "TD", name: "تشاد", dialCode: "235" },
  { code: "CL", name: "تشيلي", dialCode: "56" },
  { code: "TG", name: "توغو", dialCode: "228" },
  { code: "TV", name: "توفالو", dialCode: "688" },
  { code: "TK", name: "توكيلاو", dialCode: "690" },
  { code: "TO", name: "تونغا", dialCode: "676" },
  { code: "TL", name: "تيمور الشرقية", dialCode: "670" },
  { code: "JM", name: "جامايكا", dialCode: "1" },
  { code: "GI", name: "جبل طارق", dialCode: "350" },
  { code: "GL", name: "جرينلاند", dialCode: "299" },
  { code: "VI", name: "جزر العذراء الأمريكية", dialCode: "1" },
  { code: "VG", name: "جزر العذراء البريطانية", dialCode: "1" },
  { code: "KM", name: "جزر القمر", dialCode: "269" },
  { code: "MV", name: "جزر المالديف", dialCode: "960" },
  { code: "AX", name: "جزر أولاند", dialCode: "358" },
  { code: "TC", name: "جزر توركس وكايكوس", dialCode: "1" },
  { code: "SB", name: "جزر سليمان", dialCode: "677" },
  { code: "FO", name: "جزر فارو", dialCode: "298" },
  { code: "FK", name: "جزر فوكلاند", dialCode: "500" },
  { code: "KY", name: "جزر كايمان", dialCode: "1" },
  { code: "CK", name: "جزر كوك", dialCode: "682" },
  { code: "CC", name: "جزر كوكوس", dialCode: "61" },
  { code: "MH", name: "جزر مارشال", dialCode: "692" },
  { code: "MP", name: "جزر ماريانا الشمالية", dialCode: "1" },
  { code: "CX", name: "جزيرة عيد الميلاد", dialCode: "61" },
  { code: "IM", name: "جزيرة مان", dialCode: "44" },
  { code: "NF", name: "جزيرة نورفولك", dialCode: "672" },
  { code: "CF", name: "جمهورية أفريقيا الوسطى", dialCode: "236" },
  { code: "CZ", name: "جمهورية التشيك", dialCode: "420" },
  { code: "DO", name: "جمهورية الدومينيكان", dialCode: "1" },
  { code: "CG", name: "جمهورية الكونغو", dialCode: "242" },
  { code: "CD", name: "جمهورية الكونغو الديمقراطية", dialCode: "243" },
  { code: "ZA", name: "جنوب أفريقيا", dialCode: "27" },
  { code: "SS", name: "جنوب السودان", dialCode: "211" },
  { code: "GE", name: "جورجيا", dialCode: "995" },
  { code: "DJ", name: "جيبوتي", dialCode: "253" },
  { code: "JE", name: "جيرزي", dialCode: "44" },
  { code: "DM", name: "دومينيكا", dialCode: "1" },
  { code: "RW", name: "رواندا", dialCode: "250" },
  { code: "RU", name: "روسيا", dialCode: "7" },
  { code: "BY", name: "روسيا البيضاء", dialCode: "375" },
  { code: "RO", name: "رومانيا", dialCode: "40" },
  { code: "ZM", name: "زامبيا", dialCode: "260" },
  { code: "ZW", name: "زيمبابوي", dialCode: "263" },
  { code: "CI", name: "ساحل العاج", dialCode: "225" },
  { code: "WS", name: "ساموا", dialCode: "685" },
  { code: "AS", name: "ساموا الأمريكية", dialCode: "1" },
  { code: "BL", name: "سان بارتيلمي", dialCode: "590" },
  { code: "PM", name: "سان بيير وميكلون", dialCode: "508" },
  { code: "SM", name: "سان مارينو", dialCode: "378" },
  { code: "VC", name: "سانت فينسنت والغرينادين", dialCode: "1" },
  { code: "KN", name: "سانت كيتس ونيفيس", dialCode: "1" },
  { code: "LC", name: "سانت لوسيا", dialCode: "1" },
  { code: "MF", name: "سانت مارتن (الجزء الفرنسي)", dialCode: "590" },
  { code: "SX", name: "سانت مارتن (الجزء الهولندي)", dialCode: "1" },
  { code: "SH", name: "سانت هيلينا وأسينشين وتريستان دا كونا", dialCode: "290" },
  { code: "ST", name: "ساو تومي وبرينسيب", dialCode: "239" },
  { code: "LK", name: "سريلانكا", dialCode: "94" },
  { code: "SJ", name: "سفالبارد ويان ماين", dialCode: "47" },
  { code: "SK", name: "سلوفاكيا", dialCode: "421" },
  { code: "SI", name: "سلوفينيا", dialCode: "386" },
  { code: "SG", name: "سنغافورة", dialCode: "65" },
  { code: "SZ", name: "سوازيلاند", dialCode: "268" },
  { code: "SR", name: "سورينام", dialCode: "597" },
  { code: "CH", name: "سويسرا", dialCode: "41" },
  { code: "SL", name: "سيراليون", dialCode: "232" },
  { code: "SC", name: "سيشل", dialCode: "248" },
  { code: "RS", name: "صربيا", dialCode: "381" },
  { code: "TJ", name: "طاجيكستان", dialCode: "992" },
  { code: "GM", name: "غامبيا", dialCode: "220" },
  { code: "GH", name: "غانا", dialCode: "233" },
  { code: "GD", name: "غرينادا", dialCode: "1" },
  { code: "GT", name: "غواتيمالا", dialCode: "502" },
  { code: "GP", name: "غوادلوب", dialCode: "590" },
  { code: "GU", name: "غوام", dialCode: "1" },
  { code: "GF", name: "غويانا الفرنسية", dialCode: "594" },
  { code: "GY", name: "غيانا", dialCode: "592" },
  { code: "GG", name: "غيرنزي", dialCode: "44" },
  { code: "GN", name: "غينيا", dialCode: "224" },
  { code: "GQ", name: "غينيا الاستوائية", dialCode: "240" },
  { code: "GW", name: "غينيا بيساو", dialCode: "245" },
  { code: "VU", name: "فانواتو", dialCode: "678" },
  { code: "FR", name: "فرنسا", dialCode: "33" },
  { code: "VE", name: "فنزويلا", dialCode: "58" },
  { code: "FI", name: "فنلندا", dialCode: "358" },
  { code: "VN", name: "فيتنام", dialCode: "84" },
  { code: "FJ", name: "فيجي", dialCode: "679" },
  { code: "CY", name: "قبرص", dialCode: "357" },
  { code: "KG", name: "قيرغيزستان", dialCode: "996" },
  { code: "KZ", name: "كازاخستان", dialCode: "7" },
  { code: "NC", name: "كاليدونيا الجديدة", dialCode: "687" },
  { code: "HR", name: "كرواتيا", dialCode: "385" },
  { code: "KH", name: "كمبوديا", dialCode: "855" },
  { code: "CA", name: "كندا", dialCode: "1" },
  { code: "CU", name: "كوبا", dialCode: "53" },
  { code: "CW", name: "كوراساو", dialCode: "599" },
  { code: "KR", name: "كوريا الجنوبية", dialCode: "82" },
  { code: "KP", name: "كوريا الشمالية", dialCode: "850" },
  { code: "CR", name: "كوستاريكا", dialCode: "506" },
  { code: "XK", name: "كوسوفو", dialCode: "383" },
  { code: "CO", name: "كولومبيا", dialCode: "57" },
  { code: "KI", name: "كيريباتي", dialCode: "686" },
  { code: "KE", name: "كينيا", dialCode: "254" },
  { code: "RE", name: "لا ريونيون", dialCode: "262" },
  { code: "LV", name: "لاتفيا", dialCode: "371" },
  { code: "LA", name: "لاوس", dialCode: "856" },
  { code: "LU", name: "لوكسمبورغ", dialCode: "352" },
  { code: "LR", name: "ليبيريا", dialCode: "231" },
  { code: "LT", name: "ليتوانيا", dialCode: "370" },
  { code: "LI", name: "ليختنشتاين", dialCode: "423" },
  { code: "LS", name: "ليسوتو", dialCode: "266" },
  { code: "MQ", name: "مارتينيك", dialCode: "596" },
  { code: "MO", name: "ماكاو", dialCode: "853" },
  { code: "MW", name: "مالاوي", dialCode: "265" },
  { code: "MT", name: "مالطا", dialCode: "356" },
  { code: "ML", name: "مالي", dialCode: "223" },
  { code: "MY", name: "ماليزيا", dialCode: "60" },
  { code: "YT", name: "مايوت", dialCode: "262" },
  { code: "MG", name: "مدغشقر", dialCode: "261" },
  { code: "MK", name: "مقدونيا الشمالية", dialCode: "389" },
  { code: "MN", name: "منغوليا", dialCode: "976" },
  { code: "MR", name: "موريتانيا", dialCode: "222" },
  { code: "MU", name: "موريشيوس", dialCode: "230" },
  { code: "MZ", name: "موزمبيق", dialCode: "258" },
  { code: "MD", name: "مولدوفا", dialCode: "373" },
  { code: "MC", name: "موناكو", dialCode: "377" },
  { code: "MS", name: "مونتسرات", dialCode: "1" },
  { code: "NA", name: "ناميبيا", dialCode: "264" },
  { code: "NR", name: "ناورو", dialCode: "674" },
  { code: "NP", name: "نيبال", dialCode: "977" },
  { code: "NG", name: "نيجيريا", dialCode: "234" },
  { code: "NI", name: "نيكاراغوا", dialCode: "505" },
  { code: "NZ", name: "نيوزيلندا", dialCode: "64" },
  { code: "NU", name: "نييوي", dialCode: "683" },
  { code: "HT", name: "هايتي", dialCode: "509" },
  { code: "HN", name: "هندوراس", dialCode: "504" },
  { code: "NL", name: "هولندا", dialCode: "31" },
  { code: "HK", name: "هونغ كونغ", dialCode: "852" },
  { code: "WF", name: "والس وفوتونا", dialCode: "681" },
  { code: "FM", name: "ولايات ميكرونيسيا المتحدة", dialCode: "691" },
];
