// Generated once from i18n-iso-countries (Arabic + English names) +
// libphonenumber-js (valid calling codes). Static so the browser only
// ships the phone validation library, not the full locale dataset.
export type Country = { code: string; name: string; nameEn: string; dialCode: string };

export const COUNTRIES: Country[] = [
  { code: "SA", name: "السعودية", nameEn: "Saudi Arabia", dialCode: "966" },
  { code: "AE", name: "الإمارات العربية المتحدة", nameEn: "United Arab Emirates", dialCode: "971" },
  { code: "EG", name: "مصر", nameEn: "Egypt", dialCode: "20" },
  { code: "KW", name: "الكويت", nameEn: "Kuwait", dialCode: "965" },
  { code: "QA", name: "قطر", nameEn: "Qatar", dialCode: "974" },
  { code: "BH", name: "البحرين", nameEn: "Bahrain", dialCode: "973" },
  { code: "OM", name: "عمان", nameEn: "Oman", dialCode: "968" },
  { code: "JO", name: "الأردن", nameEn: "Jordan", dialCode: "962" },
  { code: "IQ", name: "العراق", nameEn: "Iraq", dialCode: "964" },
  { code: "SY", name: "سوريا", nameEn: "Syrian Arab Republic", dialCode: "963" },
  { code: "LB", name: "لبنان", nameEn: "Lebanon", dialCode: "961" },
  { code: "PS", name: "فلسطين", nameEn: "State of Palestine", dialCode: "970" },
  { code: "YE", name: "اليمن", nameEn: "Yemen", dialCode: "967" },
  { code: "MA", name: "المغرب", nameEn: "Morocco", dialCode: "212" },
  { code: "DZ", name: "الجزائر", nameEn: "Algeria", dialCode: "213" },
  { code: "TN", name: "تونس", nameEn: "Tunisia", dialCode: "216" },
  { code: "LY", name: "ليبيا", nameEn: "Libya", dialCode: "218" },
  { code: "SD", name: "السودان", nameEn: "Sudan", dialCode: "249" },
  { code: "IN", name: "الهند", nameEn: "India", dialCode: "91" },
  { code: "IS", name: "آيسلندا", nameEn: "Iceland", dialCode: "354" },
  { code: "ET", name: "إثيوبيا", nameEn: "Ethiopia", dialCode: "251" },
  { code: "AZ", name: "أذربيجان", nameEn: "Azerbaijan", dialCode: "994" },
  { code: "AM", name: "أرمينيا", nameEn: "Armenia", dialCode: "374" },
  { code: "AW", name: "أروبا", nameEn: "Aruba", dialCode: "297" },
  { code: "ER", name: "إريتريا", nameEn: "Eritrea", dialCode: "291" },
  { code: "ES", name: "إسبانيا", nameEn: "Spain", dialCode: "34" },
  { code: "AU", name: "أستراليا", nameEn: "Australia", dialCode: "61" },
  { code: "EE", name: "إستونيا", nameEn: "Estonia", dialCode: "372" },
  { code: "IL", name: "إسرائيل", nameEn: "Israel", dialCode: "972" },
  { code: "AF", name: "أفغانستان", nameEn: "Afghanistan", dialCode: "93" },
  { code: "IO", name: "إقليم المحيط الهندي البريطاني", nameEn: "British Indian Ocean Territory", dialCode: "246" },
  { code: "AR", name: "الأرجنتين", nameEn: "Argentina", dialCode: "54" },
  { code: "EC", name: "الإكوادور", nameEn: "Ecuador", dialCode: "593" },
  { code: "UY", name: "الأوروغواي", nameEn: "Uruguay", dialCode: "598" },
  { code: "AL", name: "ألبانيا", nameEn: "Albania", dialCode: "355" },
  { code: "BR", name: "البرازيل", nameEn: "Brazil", dialCode: "55" },
  { code: "PT", name: "البرتغال", nameEn: "Portugal", dialCode: "351" },
  { code: "BA", name: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina", dialCode: "387" },
  { code: "ME", name: "الجبل الأسود", nameEn: "Montenegro", dialCode: "382" },
  { code: "BQ", name: "الجزر الكاريبية الهولندية", nameEn: "Bonaire, Sint Eustatius and Saba", dialCode: "599" },
  { code: "DK", name: "الدنمارك", nameEn: "Denmark", dialCode: "45" },
  { code: "CV", name: "الرأس الأخضر", nameEn: "Cape Verde", dialCode: "238" },
  { code: "SV", name: "السلفادور", nameEn: "El Salvador", dialCode: "503" },
  { code: "SN", name: "السنغال", nameEn: "Senegal", dialCode: "221" },
  { code: "SE", name: "السويد", nameEn: "Sweden", dialCode: "46" },
  { code: "EH", name: "الصحراء الغربية", nameEn: "Western Sahara", dialCode: "212" },
  { code: "SO", name: "الصومال", nameEn: "Somalia", dialCode: "252" },
  { code: "CN", name: "الصين", nameEn: "People's Republic of China", dialCode: "86" },
  { code: "GA", name: "الغابون", nameEn: "Gabon", dialCode: "241" },
  { code: "VA", name: "الفاتيكان", nameEn: "Holy See (Vatican City State)", dialCode: "39" },
  { code: "PH", name: "الفلبين", nameEn: "Philippines", dialCode: "63" },
  { code: "CM", name: "الكاميرون", nameEn: "Cameroon", dialCode: "237" },
  { code: "DE", name: "ألمانيا", nameEn: "Germany", dialCode: "49" },
  { code: "HU", name: "المجر", nameEn: "Hungary", dialCode: "36" },
  { code: "MX", name: "المكسيك", nameEn: "Mexico", dialCode: "52" },
  { code: "GB", name: "المملكة المتحدة", nameEn: "United Kingdom", dialCode: "44" },
  { code: "NO", name: "النرويج", nameEn: "Norway", dialCode: "47" },
  { code: "AT", name: "النمسا", nameEn: "Austria", dialCode: "43" },
  { code: "NE", name: "النيجر", nameEn: "Niger", dialCode: "227" },
  { code: "US", name: "الولايات المتحدة", nameEn: "United States of America", dialCode: "1" },
  { code: "JP", name: "اليابان", nameEn: "Japan", dialCode: "81" },
  { code: "GR", name: "اليونان", nameEn: "Greece", dialCode: "30" },
  { code: "AG", name: "أنتيغوا وباربودا", nameEn: "Antigua and Barbuda", dialCode: "1" },
  { code: "AD", name: "أندورا", nameEn: "Andorra", dialCode: "376" },
  { code: "ID", name: "إندونيسيا", nameEn: "Indonesia", dialCode: "62" },
  { code: "AO", name: "أنغولا", nameEn: "Angola", dialCode: "244" },
  { code: "AI", name: "أنغويلا", nameEn: "Anguilla", dialCode: "1" },
  { code: "UZ", name: "أوزبكستان", nameEn: "Uzbekistan", dialCode: "998" },
  { code: "UG", name: "أوغندا", nameEn: "Uganda", dialCode: "256" },
  { code: "UA", name: "أوكرانيا", nameEn: "Ukraine", dialCode: "380" },
  { code: "IR", name: "إيران", nameEn: "Islamic Republic of Iran", dialCode: "98" },
  { code: "IE", name: "أيرلندا", nameEn: "Ireland", dialCode: "353" },
  { code: "IT", name: "إيطاليا", nameEn: "Italy", dialCode: "39" },
  { code: "PG", name: "بابوا غينيا الجديدة", nameEn: "Papua New Guinea", dialCode: "675" },
  { code: "PY", name: "باراغواي", nameEn: "Paraguay", dialCode: "595" },
  { code: "BB", name: "باربادوس", nameEn: "Barbados", dialCode: "1" },
  { code: "PK", name: "باكستان", nameEn: "Pakistan", dialCode: "92" },
  { code: "PW", name: "بالاو", nameEn: "Palau", dialCode: "680" },
  { code: "BS", name: "باهاماس", nameEn: "Bahamas", dialCode: "1" },
  { code: "BM", name: "برمودا", nameEn: "Bermuda", dialCode: "1" },
  { code: "BN", name: "بروناي", nameEn: "Brunei Darussalam", dialCode: "673" },
  { code: "BE", name: "بلجيكا", nameEn: "Belgium", dialCode: "32" },
  { code: "BG", name: "بلغاريا", nameEn: "Bulgaria", dialCode: "359" },
  { code: "BZ", name: "بليز", nameEn: "Belize", dialCode: "501" },
  { code: "BD", name: "بنغلاديش", nameEn: "Bangladesh", dialCode: "880" },
  { code: "PA", name: "بنما", nameEn: "Panama", dialCode: "507" },
  { code: "BJ", name: "بنين", nameEn: "Benin", dialCode: "229" },
  { code: "BT", name: "بوتان", nameEn: "Bhutan", dialCode: "975" },
  { code: "BW", name: "بوتسوانا", nameEn: "Botswana", dialCode: "267" },
  { code: "PR", name: "بورتوريكو", nameEn: "Puerto Rico", dialCode: "1" },
  { code: "BF", name: "بوركينا فاسو", nameEn: "Burkina Faso", dialCode: "226" },
  { code: "MM", name: "بورما", nameEn: "Myanmar", dialCode: "95" },
  { code: "BI", name: "بوروندي", nameEn: "Burundi", dialCode: "257" },
  { code: "PL", name: "بولندا", nameEn: "Poland", dialCode: "48" },
  { code: "BO", name: "بوليفيا", nameEn: "Bolivia", dialCode: "591" },
  { code: "PF", name: "بولينزيا الفرنسية", nameEn: "French Polynesia", dialCode: "689" },
  { code: "PE", name: "بيرو", nameEn: "Peru", dialCode: "51" },
  { code: "TZ", name: "تانزانيا", nameEn: "United Republic of Tanzania", dialCode: "255" },
  { code: "TH", name: "تايلاند", nameEn: "Thailand", dialCode: "66" },
  { code: "TW", name: "تايوان", nameEn: "Taiwan, Province of China", dialCode: "886" },
  { code: "TM", name: "تركمانستان", nameEn: "Turkmenistan", dialCode: "993" },
  { code: "TR", name: "تركيا", nameEn: "Türkiye", dialCode: "90" },
  { code: "TT", name: "ترينيداد وتوباغو", nameEn: "Trinidad and Tobago", dialCode: "1" },
  { code: "TD", name: "تشاد", nameEn: "Chad", dialCode: "235" },
  { code: "CL", name: "تشيلي", nameEn: "Chile", dialCode: "56" },
  { code: "TG", name: "توغو", nameEn: "Togo", dialCode: "228" },
  { code: "TV", name: "توفالو", nameEn: "Tuvalu", dialCode: "688" },
  { code: "TK", name: "توكيلاو", nameEn: "Tokelau", dialCode: "690" },
  { code: "TO", name: "تونغا", nameEn: "Tonga", dialCode: "676" },
  { code: "TL", name: "تيمور الشرقية", nameEn: "Timor-Leste", dialCode: "670" },
  { code: "JM", name: "جامايكا", nameEn: "Jamaica", dialCode: "1" },
  { code: "GI", name: "جبل طارق", nameEn: "Gibraltar", dialCode: "350" },
  { code: "GL", name: "جرينلاند", nameEn: "Greenland", dialCode: "299" },
  { code: "VI", name: "جزر العذراء الأمريكية", nameEn: "Virgin Islands, U.S.", dialCode: "1" },
  { code: "VG", name: "جزر العذراء البريطانية", nameEn: "Virgin Islands, British", dialCode: "1" },
  { code: "KM", name: "جزر القمر", nameEn: "Comoros", dialCode: "269" },
  { code: "MV", name: "جزر المالديف", nameEn: "Maldives", dialCode: "960" },
  { code: "AX", name: "جزر أولاند", nameEn: "Åland Islands", dialCode: "358" },
  { code: "TC", name: "جزر توركس وكايكوس", nameEn: "Turks and Caicos Islands", dialCode: "1" },
  { code: "SB", name: "جزر سليمان", nameEn: "Solomon Islands", dialCode: "677" },
  { code: "FO", name: "جزر فارو", nameEn: "Faroe Islands", dialCode: "298" },
  { code: "FK", name: "جزر فوكلاند", nameEn: "Falkland Islands (Malvinas)", dialCode: "500" },
  { code: "KY", name: "جزر كايمان", nameEn: "Cayman Islands", dialCode: "1" },
  { code: "CK", name: "جزر كوك", nameEn: "Cook Islands", dialCode: "682" },
  { code: "CC", name: "جزر كوكوس", nameEn: "Cocos (Keeling) Islands", dialCode: "61" },
  { code: "MH", name: "جزر مارشال", nameEn: "Marshall Islands", dialCode: "692" },
  { code: "MP", name: "جزر ماريانا الشمالية", nameEn: "Northern Mariana Islands", dialCode: "1" },
  { code: "CX", name: "جزيرة عيد الميلاد", nameEn: "Christmas Island", dialCode: "61" },
  { code: "IM", name: "جزيرة مان", nameEn: "Isle of Man", dialCode: "44" },
  { code: "NF", name: "جزيرة نورفولك", nameEn: "Norfolk Island", dialCode: "672" },
  { code: "CF", name: "جمهورية أفريقيا الوسطى", nameEn: "Central African Republic", dialCode: "236" },
  { code: "CZ", name: "جمهورية التشيك", nameEn: "Czech Republic", dialCode: "420" },
  { code: "DO", name: "جمهورية الدومينيكان", nameEn: "Dominican Republic", dialCode: "1" },
  { code: "CG", name: "جمهورية الكونغو", nameEn: "Republic of the Congo", dialCode: "242" },
  { code: "CD", name: "جمهورية الكونغو الديمقراطية", nameEn: "Democratic Republic of the Congo", dialCode: "243" },
  { code: "ZA", name: "جنوب أفريقيا", nameEn: "South Africa", dialCode: "27" },
  { code: "SS", name: "جنوب السودان", nameEn: "South Sudan", dialCode: "211" },
  { code: "GE", name: "جورجيا", nameEn: "Georgia", dialCode: "995" },
  { code: "DJ", name: "جيبوتي", nameEn: "Djibouti", dialCode: "253" },
  { code: "JE", name: "جيرزي", nameEn: "Jersey", dialCode: "44" },
  { code: "DM", name: "دومينيكا", nameEn: "Dominica", dialCode: "1" },
  { code: "RW", name: "رواندا", nameEn: "Rwanda", dialCode: "250" },
  { code: "RU", name: "روسيا", nameEn: "Russian Federation", dialCode: "7" },
  { code: "BY", name: "روسيا البيضاء", nameEn: "Belarus", dialCode: "375" },
  { code: "RO", name: "رومانيا", nameEn: "Romania", dialCode: "40" },
  { code: "ZM", name: "زامبيا", nameEn: "Zambia", dialCode: "260" },
  { code: "ZW", name: "زيمبابوي", nameEn: "Zimbabwe", dialCode: "263" },
  { code: "CI", name: "ساحل العاج", nameEn: "Cote d'Ivoire", dialCode: "225" },
  { code: "WS", name: "ساموا", nameEn: "Samoa", dialCode: "685" },
  { code: "AS", name: "ساموا الأمريكية", nameEn: "American Samoa", dialCode: "1" },
  { code: "BL", name: "سان بارتيلمي", nameEn: "Saint Barthélemy", dialCode: "590" },
  { code: "PM", name: "سان بيير وميكلون", nameEn: "Saint Pierre and Miquelon", dialCode: "508" },
  { code: "SM", name: "سان مارينو", nameEn: "San Marino", dialCode: "378" },
  { code: "VC", name: "سانت فينسنت والغرينادين", nameEn: "Saint Vincent and the Grenadines", dialCode: "1" },
  { code: "KN", name: "سانت كيتس ونيفيس", nameEn: "Saint Kitts and Nevis", dialCode: "1" },
  { code: "LC", name: "سانت لوسيا", nameEn: "Saint Lucia", dialCode: "1" },
  { code: "MF", name: "سانت مارتن (الجزء الفرنسي)", nameEn: "Saint Martin (French part)", dialCode: "590" },
  { code: "SX", name: "سانت مارتن (الجزء الهولندي)", nameEn: "Sint Maarten (Dutch part)", dialCode: "1" },
  { code: "SH", name: "سانت هيلينا وأسينشين وتريستان دا كونا", nameEn: "Saint Helena", dialCode: "290" },
  { code: "ST", name: "ساو تومي وبرينسيب", nameEn: "Sao Tome and Principe", dialCode: "239" },
  { code: "LK", name: "سريلانكا", nameEn: "Sri Lanka", dialCode: "94" },
  { code: "SJ", name: "سفالبارد ويان ماين", nameEn: "Svalbard and Jan Mayen", dialCode: "47" },
  { code: "SK", name: "سلوفاكيا", nameEn: "Slovakia", dialCode: "421" },
  { code: "SI", name: "سلوفينيا", nameEn: "Slovenia", dialCode: "386" },
  { code: "SG", name: "سنغافورة", nameEn: "Singapore", dialCode: "65" },
  { code: "SZ", name: "سوازيلاند", nameEn: "Eswatini", dialCode: "268" },
  { code: "SR", name: "سورينام", nameEn: "Suriname", dialCode: "597" },
  { code: "CH", name: "سويسرا", nameEn: "Switzerland", dialCode: "41" },
  { code: "SL", name: "سيراليون", nameEn: "Sierra Leone", dialCode: "232" },
  { code: "SC", name: "سيشل", nameEn: "Seychelles", dialCode: "248" },
  { code: "RS", name: "صربيا", nameEn: "Serbia", dialCode: "381" },
  { code: "TJ", name: "طاجيكستان", nameEn: "Tajikistan", dialCode: "992" },
  { code: "GM", name: "غامبيا", nameEn: "Republic of The Gambia", dialCode: "220" },
  { code: "GH", name: "غانا", nameEn: "Ghana", dialCode: "233" },
  { code: "GD", name: "غرينادا", nameEn: "Grenada", dialCode: "1" },
  { code: "GT", name: "غواتيمالا", nameEn: "Guatemala", dialCode: "502" },
  { code: "GP", name: "غوادلوب", nameEn: "Guadeloupe", dialCode: "590" },
  { code: "GU", name: "غوام", nameEn: "Guam", dialCode: "1" },
  { code: "GF", name: "غويانا الفرنسية", nameEn: "French Guiana", dialCode: "594" },
  { code: "GY", name: "غيانا", nameEn: "Guyana", dialCode: "592" },
  { code: "GG", name: "غيرنزي", nameEn: "Guernsey", dialCode: "44" },
  { code: "GN", name: "غينيا", nameEn: "Guinea", dialCode: "224" },
  { code: "GQ", name: "غينيا الاستوائية", nameEn: "Equatorial Guinea", dialCode: "240" },
  { code: "GW", name: "غينيا بيساو", nameEn: "Guinea-Bissau", dialCode: "245" },
  { code: "VU", name: "فانواتو", nameEn: "Vanuatu", dialCode: "678" },
  { code: "FR", name: "فرنسا", nameEn: "France", dialCode: "33" },
  { code: "VE", name: "فنزويلا", nameEn: "Venezuela", dialCode: "58" },
  { code: "FI", name: "فنلندا", nameEn: "Finland", dialCode: "358" },
  { code: "VN", name: "فيتنام", nameEn: "Vietnam", dialCode: "84" },
  { code: "FJ", name: "فيجي", nameEn: "Fiji", dialCode: "679" },
  { code: "CY", name: "قبرص", nameEn: "Cyprus", dialCode: "357" },
  { code: "KG", name: "قيرغيزستان", nameEn: "Kyrgyzstan", dialCode: "996" },
  { code: "KZ", name: "كازاخستان", nameEn: "Kazakhstan", dialCode: "7" },
  { code: "NC", name: "كاليدونيا الجديدة", nameEn: "New Caledonia", dialCode: "687" },
  { code: "HR", name: "كرواتيا", nameEn: "Croatia", dialCode: "385" },
  { code: "KH", name: "كمبوديا", nameEn: "Cambodia", dialCode: "855" },
  { code: "CA", name: "كندا", nameEn: "Canada", dialCode: "1" },
  { code: "CU", name: "كوبا", nameEn: "Cuba", dialCode: "53" },
  { code: "CW", name: "كوراساو", nameEn: "Curaçao", dialCode: "599" },
  { code: "KR", name: "كوريا الجنوبية", nameEn: "South Korea", dialCode: "82" },
  { code: "KP", name: "كوريا الشمالية", nameEn: "North Korea", dialCode: "850" },
  { code: "CR", name: "كوستاريكا", nameEn: "Costa Rica", dialCode: "506" },
  { code: "XK", name: "كوسوفو", nameEn: "Kosovo", dialCode: "383" },
  { code: "CO", name: "كولومبيا", nameEn: "Colombia", dialCode: "57" },
  { code: "KI", name: "كيريباتي", nameEn: "Kiribati", dialCode: "686" },
  { code: "KE", name: "كينيا", nameEn: "Kenya", dialCode: "254" },
  { code: "RE", name: "لا ريونيون", nameEn: "Reunion", dialCode: "262" },
  { code: "LV", name: "لاتفيا", nameEn: "Latvia", dialCode: "371" },
  { code: "LA", name: "لاوس", nameEn: "Lao People's Democratic Republic", dialCode: "856" },
  { code: "LU", name: "لوكسمبورغ", nameEn: "Luxembourg", dialCode: "352" },
  { code: "LR", name: "ليبيريا", nameEn: "Liberia", dialCode: "231" },
  { code: "LT", name: "ليتوانيا", nameEn: "Lithuania", dialCode: "370" },
  { code: "LI", name: "ليختنشتاين", nameEn: "Liechtenstein", dialCode: "423" },
  { code: "LS", name: "ليسوتو", nameEn: "Lesotho", dialCode: "266" },
  { code: "MQ", name: "مارتينيك", nameEn: "Martinique", dialCode: "596" },
  { code: "MO", name: "ماكاو", nameEn: "Macao", dialCode: "853" },
  { code: "MW", name: "مالاوي", nameEn: "Malawi", dialCode: "265" },
  { code: "MT", name: "مالطا", nameEn: "Malta", dialCode: "356" },
  { code: "ML", name: "مالي", nameEn: "Mali", dialCode: "223" },
  { code: "MY", name: "ماليزيا", nameEn: "Malaysia", dialCode: "60" },
  { code: "YT", name: "مايوت", nameEn: "Mayotte", dialCode: "262" },
  { code: "MG", name: "مدغشقر", nameEn: "Madagascar", dialCode: "261" },
  { code: "MK", name: "مقدونيا الشمالية", nameEn: "The Republic of North Macedonia", dialCode: "389" },
  { code: "MN", name: "منغوليا", nameEn: "Mongolia", dialCode: "976" },
  { code: "MR", name: "موريتانيا", nameEn: "Mauritania", dialCode: "222" },
  { code: "MU", name: "موريشيوس", nameEn: "Mauritius", dialCode: "230" },
  { code: "MZ", name: "موزمبيق", nameEn: "Mozambique", dialCode: "258" },
  { code: "MD", name: "مولدوفا", nameEn: "Moldova, Republic of", dialCode: "373" },
  { code: "MC", name: "موناكو", nameEn: "Monaco", dialCode: "377" },
  { code: "MS", name: "مونتسرات", nameEn: "Montserrat", dialCode: "1" },
  { code: "NA", name: "ناميبيا", nameEn: "Namibia", dialCode: "264" },
  { code: "NR", name: "ناورو", nameEn: "Nauru", dialCode: "674" },
  { code: "NP", name: "نيبال", nameEn: "Nepal", dialCode: "977" },
  { code: "NG", name: "نيجيريا", nameEn: "Nigeria", dialCode: "234" },
  { code: "NI", name: "نيكاراغوا", nameEn: "Nicaragua", dialCode: "505" },
  { code: "NZ", name: "نيوزيلندا", nameEn: "New Zealand", dialCode: "64" },
  { code: "NU", name: "نييوي", nameEn: "Niue", dialCode: "683" },
  { code: "HT", name: "هايتي", nameEn: "Haiti", dialCode: "509" },
  { code: "HN", name: "هندوراس", nameEn: "Honduras", dialCode: "504" },
  { code: "NL", name: "هولندا", nameEn: "Netherlands", dialCode: "31" },
  { code: "HK", name: "هونغ كونغ", nameEn: "Hong Kong", dialCode: "852" },
  { code: "WF", name: "والس وفوتونا", nameEn: "Wallis and Futuna", dialCode: "681" },
  { code: "FM", name: "ولايات ميكرونيسيا المتحدة", nameEn: "Micronesia, Federated States of", dialCode: "691" },
];
